### ISSUE TITLE
Allow updating specific template values

### ISSUE THREAD

**Issue by maxice8** [Cogitri/tmplgen#7]
We can currently "update" a template by passing the "-f" switch to override it.

Problem is that it will discard all our progress.

Create a -u switch that updates the version=, checksum=, distfiles= and homepage= values.

**Comment by Cogitri** [comment]
Should homepage & distfiles really be updated unconditionally, or should that be optional?

Also: Should we do the update thingie as a separate binary or as a switch? A separate binary would mean that tmplgen would turn out about twice as big (due to static linking) and cause some code duplication, but would make the separation a little cleaner.

**Comment by Cogitri** [comment]
> Problably optional, -u -U ?

Sounds good.

> Your call, i don't work on the code

Ah, I'm more concerned about usability, as I heard quite a few ppl who are a little confused by how xbps is split up into multiple binaries. I guess I'll just do it as a switch, we can always split it later on.

**Comment by Cogitri** [comment]
I've attached a binary for testing.

[tmplgen-v0.6.0-binary.tar.gz](https://github.com/Cogitri/tmplgen/files/2631093/tmplgen-v0.6.0-binary.tar.gz)

**Comment by maxice8** [comment]
Tested on ruby-faraday.
